version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - unit
            - app
        ulimits:
            nproc: 819200
            nofile: 819200

    unit:
        image: mrsuh/php-load-test-nginx-unit:1.0.0
        expose:
            - 8300
        volumes:
            - app-volume:/app:cached

    app:
        image: mrsuh/php-load-test-app:1.0.0
        volumes:
            - app-volume:/app

volumes:
    app-volume: