version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
            - app
        ulimits:
            nproc: 819200
            nofile: 819200

    php:
        image: mrsuh/php-load-test-php-cli:1.0.0
        working_dir: /app
        environment:
            TIMEZONE: Europe/Paris
            APP_ENV: prod
            APP_TYPE: react-php
        volumes:
            - app-volume:/app:cached
        expose:
            - 9000
        command:
            - /app/bin/react-worker.php

    app:
        image: mrsuh/php-load-test-app:1.0.0
        volumes:
            - app-volume:/app

volumes:
    app-volume: