version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
            - app-volume:/app:cached
        depends_on:
            - php
            - app
        ulimits:
            nproc: 819200
            nofile: 819200

    php:
        image: mrsuh/php-load-test-php-cli:1.0.0
        hostname: php
        working_dir: /app
        expose:
            - 9000
        environment:
            TIMEZONE: Europe/Paris
            APP_ENV: prod
            APP_TYPE: php-ppm
        volumes:
            - app-volume:/app:cached
            - ./php-cli/config.json:/app/config.json
        command:
            - /app/vendor/bin/ppm
            - start
            - --config=/app/config.json
    app:
        image: mrsuh/php-load-test-app:1.0.0
        volumes:
            - app-volume:/app

volumes:
    app-volume: